### ISSUE TITLE
Where does mapzen.whosonfirst.placetypes come from?

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen-www-places#24]
I see it imported in `server.py`, but I can’t find a mention in the various installation scripts.

**Comment by thisisaaronland** [comment]
Oh yeah, those need to be updated. That got added yesterday...

`easy_install https://github.com/whosonfirst/py-mapzen-whosonfirst-placetypes/tarball/master`

**Comment by thisisaaronland** [comment]
That is now included as part of the `setup-dependencies.sh` script.

**Comment by migurski** [comment]
Great! Can I recommend `pip` instead of `easy_install`?

**Comment by thisisaaronland** [comment]
My understanding is that pip expects scripts, etc. to be laid out in very specific ways that don't warrant the time to refactor right now (maybe when we support Python 3 for all the things).

If I am wrong about that then I just need pointers for what to do.

**Comment by migurski** [comment]
It’s a drop-in replacement the way you're using it. Replace every instance of `easy_install` with `pip install` to reap the benefits of an extra half-decade of development:

```
pip install https://github.com/whosonfirst/py-mapzen-whosonfirst-placetypes/tarball/master
```

**Comment by thisisaaronland** [comment]
What are these benefits?

**Comment by migurski** [comment]
It’ll make it easier to select a Python version on Circle, so that we can connect this to Precog. Circle uses Virtualenv’s, which _might_ work with `easy_install` but basically nobody tests with it anymore.

**Comment by thisisaaronland** [comment]
Done. I note with interest that `apt` still refers to pip as the "alternative package manager" for Python.

**Comment by migurski** [comment]
Heh. I think those descriptions are forever.
